### ISSUE TITLE
About the data preprocessing

### ISSUE THREAD

**Issue by Wangrui-berry** [czifan/MuMo#4]
In the file of utils.py, there are two preprocessing methods for missing data, one as a torch.FloatTensor([0.0, 0.0]), and the other as NotImplementedError (np. nan?). How do we distinguish them? When and why use the torch.FloatTensor([0.0, 0.0]) or np. nan is more appropriate? Thanks for your time.

    def ccd_yx_stomach(pid_dir):
        # 影像：有无原发灶
        if os.path.isdir(pid_dir):
            stomach_files = [file for file in glob(os.path.join(pid_dir, "v_stomach*.jpg")) if not file.endswith("_mask.jpg")]
            if len(stomach_files):
                return torch.FloatTensor([0.0, 1.0]) # 有原发灶
            else:
                return torch.FloatTensor([1.0, 0.0]) # 无原发灶
        else:
            return torch.FloatTensor([0.0, 0.0])
        
     def ccd_time(x):
        # 患者：开始治疗时间
        if int(x) >= 2007 and int(x) < 2012:
            return torch.FloatTensor([1.0, 0.0, 0.0])
        elif int(x) >= 2012 and int(x) < 2017:
            return torch.FloatTensor([0.0, 1.0, 0.0])
        elif int(x) >= 2017 and int(x) <= 2023:
            return torch.FloatTensor([0.0, 0.0, 1.0])
        else:
            raise NotImplementedError

**Comment by czifan** [comment]
> In the file of utils.py, there are two preprocessing methods for missing data, one as a torch.FloatTensor([0.0, 0.0]), and the other as NotImplementedError (np. nan?). How do we distinguish them? When and why use the torch.FloatTensor([0.0, 0.0]) or np. nan is more appropriate? Thanks for your time.
> 
> ```
> def ccd_yx_stomach(pid_dir):
>     # 影像：有无原发灶
>     if os.path.isdir(pid_dir):
>         stomach_files = [file for file in glob(os.path.join(pid_dir, "v_stomach*.jpg")) if not file.endswith("_mask.jpg")]
>         if len(stomach_files):
>             return torch.FloatTensor([0.0, 1.0]) # 有原发灶
>         else:
>             return torch.FloatTensor([1.0, 0.0]) # 无原发灶
>     else:
>         return torch.FloatTensor([0.0, 0.0])
>     
>  def ccd_time(x):
>     # 患者：开始治疗时间
>     if int(x) >= 2007 and int(x) < 2012:
>         return torch.FloatTensor([1.0, 0.0, 0.0])
>     elif int(x) >= 2012 and int(x) < 2017:
>         return torch.FloatTensor([0.0, 1.0, 0.0])
>     elif int(x) >= 2017 and int(x) <= 2023:
>         return torch.FloatTensor([0.0, 0.0, 1.0])
>     else:
>         raise NotImplementedError
> ```

Thank you for your question!

The placeholder [0.0, 0.0] is typically used to represent edge cases in the data, such as when some data points are missing. On the other hand, NotImplementedError is used for data integrity checks during engineering. Since all our data for treatment start times falls between 2007 and 2023, anything outside this range indicates a potential data issue, which is why we use NotImplementedError. If additional data outside this range is expected, we recommend using an appropriate placeholder.

On a related note, our latest work suggests that using nn.Embedding to represent clinical features is more natural and often leads to better results. Additionally, this approach eliminates the need to manually configure the relationship between clinical information and one-hot encoding.

I hope this response helps!
